### ISSUE TITLE
System.NotSupportedException: Specified method is not supported

### ISSUE THREAD

**Issue by milos12345** [Grabacr07/VirtualDesktop#56]
I get this Stack Trace by automatic crash report of my program that users VirtualDesktop

```
System.NotSupportedException: Specified method is not supported.
   at WindowsDesktop.Interop.VirtualDesktopManagerInternal.GetInstance()
   at WindowsDesktop.Interop.ComObjects.Initialize()
   at WindowsDesktop.Interop.ComObjects.ExplorerRestartListenerWindow.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
`OSVersion: Microsoft Windows NT 10.0.21337.0`

I don't get additional information to know what the user did to cause this but I would like to know how I can prevent the crash.

**Comment by anaisbetts** [comment]
This is #55
